apiVersion: v1alpha1
name: jenkins-pipeline-config
metadata:
  labels:
    com.know-ops.ci/tool: jenkins
    com.know-ops.ci.jenkins/config: core
spec:
  dir: '.jenkins/'

  autodetect:
    language: true
    tool: true
    type: true

  project:
    platform: kubernetes

  development:
    platform: kubernetes