kubernetes:
  default: &k8sDefault 
    type: kubernetes

  project:
    autodetect:
      <<: *k8sDefault
      
      labels:
      - k8s-project-agent

  development:
    java: &javaAgents
      <<: *k8sDefault

      labels:
      - k8s-openjdk8-agent
      - k8s-openjdk11-agent
      - k8s-openjdk14-agent

      matrix: true
      fast-fail: false

    groovy: 
      <<: *javaAgents

    kotlin: 
      <<: *javaAgents

    kaniko: &kanikoAgent
      <<: *k8sDefault

      labels:
      - k8s-kaniko-agent

      matrix: false
      fast-fail: false

  release:
    github:
      <<: *k8sDefault

      labels:
      - k8s-github-agent

    kaniko: 
    <<: *kanikoAgent
