apiVersion: v1alpha1
name: jenkins-pipeline-platforms
metadata:
  labels:
    com.know-ops.ci/tool: jenkins
    com.know-ops.ci.jenkins/config: projects
spec:
  jenkins-library:
    platform:
      development: kubernetes
      release: kubernetes
      deployment: kubernetes

    nodes:
      development:
        groovy:
          labels:
          - k8s-openjdk8-agent

        kotlin: {}

        matrix: false
